package events;

import java.awt.Color;

import cards.HandManager;
import game.GameData;
import main.Launcher;

public class RedScare extends Card {

	@Override
	public void onEvent(int sp, String[] args) {
		CardEmbedBuilder builder = new CardEmbedBuilder();
		if (sp==0) {
			builder.setTitle("Purge!")
			.setDescription("Stalinist paranoia leads to arrest of hundreds of Communist Party members")
			.setColor(Color.blue)
			.setFooter("\"I know that after my death a pile of rubbish will be heaped on my grave, but the wind of History will sooner or later sweep it away without mercy.\"\n"
					+ "- Joseph Stalin, 1943", Launcher.url("people/stalin.png"));
			builder.addField("Gulag Archipelago","The USSR subtracts 1 Operations point from any card played for operations.",false);
			HandManager.addEffect(311);
		}
		else {
			builder.setTitle("Red Scare!")
			.setDescription("McCarthyist paranoia sows distrust")
			.setColor(Color.red)
			.setFooter("\"Nothing would probably please him more than to get the publicity that would be generated by a public repudiation by the President.\"\n"
					+ "- Dwight David Eisenhower, quoted 1988", Launcher.url("people/eisenhower.png"));
			builder.addField("Blacklisted","The US subtracts 1 Operations point from any card played for operations.",false);
			HandManager.addEffect(310);
		}
		
		GameData.txtchnl.sendMessage(builder.build()).complete();
	}

	@Override
	public boolean isPlayable(int sp) {
		// TODO Auto-generated method stub
		return !(GameData.ccw&&sp==1&&HandManager.China==-1);
	}

	@Override
	public String getId() {
		// TODO Auto-generated method stub
		return "031";
	}

	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return "Red Scare/Purge";
	}

	@Override
	public int getOps() {
		// TODO Auto-generated method stub
		return 4;
	}

	@Override
	public int getEra() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int getAssociation() {
		// TODO Auto-generated method stub
		return 2;
	}

	@Override
	public boolean isRemoved() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isFormatted(int sp, String[] args) {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return "The opposing player deducts one Operations Point on every card played by that side for every purpose for the remainder of this turn.";
	}

	@Override
	public String getArguments() {
		// TODO Auto-generated method stub
		return "None.";
	}

}
